### ISSUE TITLE
As any type of user, I want to login/logout of app

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/feelit-chips-backend#19]
- [x] Create `Users` collection in MongoDB #20 
- [x] Create `/login` route #21
- [x] Create `/signout` route #22
