### ISSUE TITLE
As an admin user, I want to manage and securely invite new employees to sign up to app

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/feelit-chips-backend#26]
- [x] Research how to create a secure link to employees to sign up #27 
- [x] Create `/get-all-users` route #30 
- [x] Create `/delete-user/:_id` route  #31
- [x] Create `/sign-up/:token` #38
